name: yolo11
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==1.24.4
      - opencv-python==4.10.0.84
      - torch==2.4.1
      - torchvision==0.19.1
      - ultralytics==8.3.3
      - pygame==2.6.1
      - Pillow==10.4.0
      - matplotlib==3.7.5
      - scipy==1.10.1
      - pydantic==2.9.1
      - PyYAML==6.0.1
      - tqdm==4.66.5


